### ISSUE TITLE
error: invalid conversion from 'void*' to 'gpio_regs*' 

### ISSUE THREAD

**Issue by ludekvodicka** [StefanBruens/ESP8266_new_pwm#10]
Hi,

I'm testing your library but unfortunately I'm not able to get it work. 

    sketch\pwm.c:96:51: error: invalid conversion from 'void*' to 'gpio_regs*' [-fpermissive]
    static struct gpio_regs* gpio = (void*)(0x60000300);
    
    sketch\pwm.c:110:53: error: invalid conversion from 'void*' to 'timer_regs*' [-fpermissive]
    static struct timer_regs* timer = (void*)(0x60000600);

The problem seems to be in casting constant to pointer to struct.

**Comment by StefanBruens** [comment]
Fixed, thanks for pointing this out.
