### ISSUE TITLE
Arduino ide

### ISSUE THREAD

**Issue by quantumKernel** [StefanBruens/ESP8266_new_pwm#22]
Can you explain how to use your library with ide?

**Comment by StefanBruens** [comment]
No, I don't use the crappy Arduino IDE.
Others have apparently done it, so it is possible.

**Comment by stanelie** [comment]
Working example here (I was looking for something similar myself) : 
https://github.com/JoaoLopesF/ESP8266-Arduino-PWM-SDK-Sample
